### ISSUE TITLE
Add to coredns.io/exmiddleware?

### ISSUE THREAD

**Issue by miekg** [creamfinance/coredns-dbcheck#5]
if you feel this middleware does more than crash on startup it might be worth adding it on https://coredns.io/exmiddleware for some extra exposure. Of course you should probably add *highly experimental* or any other warning in the README for the time being....

See https://coredns.io/2017/07/23/add-external-middleware/

**Comment by miekg** [comment]
Friendly ping,  should I add it there (with a work-in-progress notice)?

**Comment by thoro** [comment]
if you believe it's interesting for users please do so, but I am currently completely swamped with other stuff, so probably won't extend it with additional features until I actually need them.

**Comment by miekg** [comment]
ack - I won't then.
